//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quab_Ly_ne_nep_thi_dua.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhGia
    {
        public int IdDanhGia { get; set; }
        public Nullable<int> IdLop { get; set; }
        public Nullable<decimal> TongDiem { get; set; }
        public string XepLoai { get; set; }
        public string Tuan { get; set; }
        public string Thang { get; set; }
        public string HocKy { get; set; }
        public string NamHoc { get; set; }
 
        public virtual Lop Lop { get; set; }
    }
}
