//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quab_Ly_ne_nep_thi_dua.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DiemNeNep
    {
        [Key]
        public int IdDiemnn { get; set; }

        [Display(Name = "ID Lớp")]
        public Nullable<int> IdLop { get; set; }

        [Display(Name = "Điểm Nề Nếp")]
        [Required(ErrorMessage = "Không có điểm nề nếp tuần, tháng, năm, học kỳ này .")]
        public Nullable<decimal> DiemNeNep1 { get; set; }

        [Display(Name = "Ngày Cập Nhật")]
        public Nullable<System.DateTime> NgayCapNhat { get; set; }

        [Display(Name = "Tuần")]
        [Required(ErrorMessage = "Vui lòng chọn tuần.")]
        public string Tuan { get; set; }

        [Display(Name = "Tháng")]
        [Required(ErrorMessage = "Vui lòng chọn tháng.")]
        public string Thang { get; set; }

        [Display(Name = "Học Kỳ")]
        [Required(ErrorMessage = "Vui lòng chọn học kỳ.")]
        public string HocKy { get; set; }

        [Display(Name = "Năm Học")]
        [Required(ErrorMessage = "Vui lòng chọn năm học.")]
        public string NamHoc { get; set; }
        public virtual Lop Lop { get; set; }
    }
}
