//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quab_Ly_ne_nep_thi_dua.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Lop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lop()
        {
            this.DanhGias = new HashSet<DanhGia>();
            this.DiemHocTaps = new HashSet<DiemHocTap>();
            this.DiemNeNeps = new HashSet<DiemNeNep>();
            this.HocSinhs = new HashSet<HocSinh>();
        }
        [Key]
        public int IdLop { get; set; }
        [Display(Name = "Tên Lớp")]
        [Required(ErrorMessage = "Vui lòng nhập tên lớp.")]
        [RegularExpression(@"^(1[1-2]|12)A([1-9]|[1-9][0-9])$", ErrorMessage = "Tên lớp không hợp lệ.(11...12 + A + 1...99. Ví dụ: 12A3   )")]
        public string TenLop { get; set; }

        [Display(Name = "Năm Học")]
        [Required(ErrorMessage = "Vui lòng nhập năm học.")]
        public string NamHoc { get; set; }

        [Display(Name = "Giáo Viên Chủ Nhiệm")]
        [Required(ErrorMessage = "Vui lòng chọn giáo viên chủ nhiệm.")]
        public Nullable<int> IdGVCN { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhGia> DanhGias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiemHocTap> DiemHocTaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiemNeNep> DiemNeNeps { get; set; }
        public virtual GVCN GVCN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HocSinh> HocSinhs { get; set; }
    }
}
