//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quab_Ly_ne_nep_thi_dua.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TaiKhoan
    {
        [Key]
        public int IdTaiKhoan { get; set; }

        [Display(Name = "Tên Đăng Nhập")]
        [Required(ErrorMessage = "Vui lòng nhập tên đăng nhập.")]
        [MinLength(10, ErrorMessage = "Tài khoản phải ít nhất 10 ký tự")]
        public string TenDangNhap { get; set; }

        [Display(Name = "Mật Khẩu")]
        [Required(ErrorMessage = "Vui lòng nhập mật khẩu.")]
        [MinLength(6, ErrorMessage = "Mật khẩu phải có ít nhất 6 ký tự")]
        public string MatKhau { get; set; }



        [Display(Name = "Vai trò")]
        [Required(ErrorMessage = "Vui lòng chọn vai trò.")]
        public int QuyenTruyCap { get; set; }

        [Display(Name = "Trạng Thái")]
        [Required(ErrorMessage = "Vui lòng chọn trạng thái.")]
        public bool TrangThai { get; set; }
    }
}
