//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quab_Ly_ne_nep_thi_dua.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ViPham
    {
        [Key]
        public int IdViPham { get; set; }
        [Display(Name = "Học Sinh")]
        [Required(ErrorMessage = "Vui lòng chọn học sinh.")]
        public Nullable<int> IdHocSinh { get; set; }

        [Display(Name = "Loại Vi Phạm")]
        [Required(ErrorMessage = "Vui lòng chọn loại vi phạm.")]
        public string LoaiViPham { get; set; }

        [Display(Name = "Mô Tả Vi Phạm")]
        public string MoTaViPham { get; set; }

        [Display(Name = "Ngày Vi Phạm")]
        [Required(ErrorMessage = "Vui lòng chọn ngày vi phạm.")]
        public DateTime NgayViPham { get; set; }

        [Display(Name = "Tên Tuần")]
        [Required(ErrorMessage = "Vui lòng chọn tên tuần.")]
        public string TenTuan { get; set; }
        public Nullable<decimal> DiemTru { get; set; }
        public string Thang { get; set; }
        public string HocKy { get; set; }
        public string NamHoc { get; set; }
        //[Key]
        //public int IdViPham { get; set; }

        //public Nullable<int> IdHocSinh { get; set; }

        //[Display(Name = "Loại Vi Phạm")]
        //[Required(ErrorMessage = "Vui lòng chọn loại vi phạm.")]
        //public string LoaiViPham { get; set; }

        //[Display(Name = "Mô Tả Vi Phạm")]

        //public string MoTaViPham { get; set; }

        //[Display(Name = "Ngày Vi Phạm")]
        //[Required(ErrorMessage = "Vui lòng chọn ngày vi phạm.")]
        //public DateTime NgayViPham { get; set; }

        //[Display(Name = "Tên Tuần")]
        //[Required(ErrorMessage = "Vui lòng chọn tên tuần.")]
        //public string TenTuan { get; set; }

        //[Display(Name = "Điểm Trừ")]
        //public Nullable<decimal> DiemTru { get; set; }

        //[Display(Name = "Tháng")]
        //[Required(ErrorMessage = "Vui lòng chọn tháng.")]
        //public string Thang { get; set; }

        //[Display(Name = "Học Kỳ")]
        //[Required(ErrorMessage = "Vui lòng chọn học kỳ.")]
        //public string HocKy { get; set; }

        //[Display(Name = "Năm Học")]
        //[Required(ErrorMessage = "Vui lòng chọn năm học.")]
        //public string NamHoc { get; set; }

        public virtual HocSinh HocSinh { get; set; }
    }
}
